// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elwaqwtbuqwhgaivbiip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsd2Fxd3RidXF3aGdhaXZiaWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTgxOTMsImV4cCI6MjA2NDIzNDE5M30.wCc7-FI1ywyQ5wNsYPiZlm6m-DcAsrA0AEj7wKutHkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);